name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Cache Docker layers
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ github.ref }}-docker-layer-cache
        restore-keys: ${{ github.ref }}-docker-layer-cache

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    # Push Docker image to a registry
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push image to Docker Hub
      run: docker push my-image-name:latest
